spring:
    application:
        name: xmock-satellite
server:
    port: 9000

management:
  port: 10999
  context-path: /admin
  security:
    enabled: false

port:
  range:
    min: 8000
    max: 30000

endpoints:
  restart:
    enabled: true